openapi: 3.0.3
info:
  title: Smart Resilience Services example container
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 2.2.2
components:
  schemas:
    pick:
      $ref: ./api/schemas/pick.yaml
    trend:
      $ref: ./api/schemas/trend.yaml
  securitySchemes:
    BasicUser:
      type: http
      scheme: basic

paths:
  /pics:
    $ref: ./api/operations/picks.yaml
  /trends:
    $ref: ./api/operations/trend.yaml